version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/:/backend/
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build/:/usr/share/nginx/html/
    depends_on:
      - backend
